import { buildReportStory } from "./story.js";
import type { ReportData } from "./types.js";

/** 테스트·빈 리포트용 최소 ReportData */
export function emptyReportData(): ReportData {
  const insights = {
    weekendSharePercent: 0,
    participantGini: null,
    replyGapP90Minutes: null,
    maxSilenceBetweenActiveDays: null,
    top3ParticipantSharePercent: 0,
    linkDomainEntropyBits: null,
    densityMessagesPerCalendarDay: null,
    questionLikeMessagesPer100: 0,
    speakerSwitchRatePer100: 0,
    rhythmScore: 0,
    daypartPercents: [
      { key: "dawn", label: "새벽(0~5시)", percent: 0 },
      { key: "morning", label: "오전(6~11시)", percent: 0 },
      { key: "afternoon", label: "오후(12~17시)", percent: 0 },
      { key: "evening", label: "저녁(18~23시)", percent: 0 },
    ],
    linksPer100: 0,
    attachmentsPer100: 0,
    medianMessagesPerParticipant: null,
    burstGapUnder1mPercent: null,
    gapOver60mPercent: null,
    activeHoursCount: 0,
    keywordTop1SharePercent: null,
    photoShareOfAllAttachmentMarkers: null,
    monologueMessagesPercent: 0,
    peakDaySharePercent: 0,
    uniqueDomainCount: 0,
    replyGapCoeffVariation: null,
    lexicalTypeRichnessPercent: null,
    sessionCount: 0,
    avgMessagesPerSession: null,
    medianSessionMinutes: null,
  };
  const story = buildReportStory({
    chatRoomName: "채팅방",
    totalMessages: 0,
    activeDays: 0,
    firstMessage: null,
    lastMessage: null,
    longestStreak: 0,
    peakHour: null,
    busiestWeekdayLabel: null,
    nightSharePercent: 0,
    emojiMessages: 0,
    participants: [],
    daily: [],
    dailySenderCounts: new Map(),
    senderAliases: new Map(),
    insights,
    laughMessages: 0,
    shortMessages: 0,
    laughBySender: new Map(),
    shortBySender: new Map(),
    burstDays: [],
    activityArc: [{ id: "whole", label: "전체", messages: 0, activeDays: 0 }],
    conversationPace: { label: "혼합 리듬", emoji: "🌊", detail: "데이터 없음" },
    roomPulse: [],
  });
  return {
    generatedAt: "2026-05-16T00:00:00.000Z",
    privacy: "public-masked",
    source: {
      fileName: "KakaoTalk export",
      chatRoomName: "채팅방",
      encoding: "utf-8",
      physicalLines: 1,
      warnings: 0,
    },
    summary: {
      totalMessages: 0,
      participants: 0,
      activeDays: 0,
      firstMessage: null,
      lastMessage: null,
      averageMessageLength: 0,
      messagesWithLinks: 0,
      messagesWithAttachments: 0,
      messagesPerActiveDay: 0,
      longestActiveStreakDays: 0,
      peakHour: null,
      busiestWeekdayLabel: null,
      medianReplyGapMinutes: null,
      nightSharePercent: 0,
      emojiMessages: 0,
    },
    insights,
    participants: [],
    daily: [],
    hourly: Array.from({ length: 24 }, () => 0),
    weekdays: ["일", "월", "화", "수", "목", "금", "토"].map((d) => ({ label: `${d}요일`, count: 0 })),
    monthly: [],
    attachments: [],
    domains: [],
    keywords: [],
    topics: [],
    roomEvents: {
      joinCount: 0,
      leaveCount: 0,
      deletedCount: 0,
      hiddenCount: 0,
      kickCount: 0,
      slowModeOnCount: 0,
      slowModeOffCount: 0,
      subManagerCount: 0,
      managerCount: 0,
      shopSearchCount: 0,
      photoBundleCount: 0,
      total: 0,
      joinSharePercent: 0,
      leaveSharePercent: 0,
      deletedSharePercent: 0,
      hiddenSharePercent: 0,
      kickSharePercent: 0,
    },
    repeatedPhrases: [],
    shopSearchTopics: [],
    pureLaughMessages: 0,
    conversationPace: { label: "혼합 리듬", emoji: "🌊", detail: "데이터 없음" },
    burstDays: [],
    activityArc: [{ id: "whole", label: "전체", messages: 0, activeDays: 0 }],
    roomPulse: [],
    highlights: [],
    story,
    interaction: null,
    timeline: [],
    narrative: { ogSummary: "빈 리포트", paragraphs: [] },
    periodCompare: {
      slices: [{ id: "whole", label: "전체", messages: 0, activeDays: 0, messagesPerActiveDay: 0 }],
      keywordShift: { head: [], tail: [], onlyHead: [], onlyTail: [] },
    },
    benchmarks: [],
    openChatBoilerplateExcluded: 0,
    burstDetectionMethod: "heuristic",
    explorer: { daily: [], hourly: [], monthly: [], range: { min: "", max: "" } },
  };
}
